src/Entity/Challenge.php
<?php

namespace App\Entity;

use App\Repository\ChallengeRepository;
use App\Traits\NameTrait;
use App\Traits\PositionTrait;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChallengeRepository::class)
 */
class Challenge extends Entity
{
    use NameTrait, PositionTrait;

    /**
     * @ORM\Column(type="text")
     */
    private string $content;

    /**
     * @ORM\Column(type="array")
     */
    private array $answers = [];

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $link = null;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private ?int $score = 0;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private ?string $note = null;

    /**
     * @ORM\ManyToOne(targetEntity=ChallengeCategory::class, inversedBy="challenge")
     * @ORM\JoinColumn(nullable=false)
     */
    private ChallengeCategory $category;

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return array
     */
    public function getAnswers(): array
    {
        return $this->answers;
    }

    /**
     * @param array $answers
     * @return Challenge
     */
    public function setAnswers(array $answers): Challenge
    {
        $this->answers = $answers;
        return $this;
    }

    public function getLink(): ?string
    {
        return $this->link;
    }

    public function setLink(?string $link): self
    {
        $this->link = $link;

        return $this;
    }

    public function getScore(): ?int
    {
        return $this->score;
    }

    public function setScore(?int $score): self
    {
        $this->score = $score;

        return $this;
    }

    public function getNote(): ?string
    {
        return $this->note;
    }

    public function setNote(?string $note): self
    {
        $this->note = $note;

        return $this;
    }

    public function getCategory(): ?ChallengeCategory
    {
        return $this->category;
    }

    public function setCategory(ChallengeCategory $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function getSection(): ?ChallengeSection
    {
        return $this->category->getSection();
    }
}

src/Form/ChallengeType.php
<?php

namespace App\Form;

use App\Entity\Challenge;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ChallengeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name')
            ->add('content', TextareaType::class, [
                'attr' => ['rows' => 5]
            ])
            ->add('answers', CollectionType::class, [
                'entry_type' => TextType::class,
                'label' => false,
                'allow_add' => true,
                'allow_delete' => true,
                'prototype' => true
            ])
            ->add('link', TextType::class, [
                'required' => false
            ])
            ->add('note', TextareaType::class, [
                'required' => false
            ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Challenge::class,
        ]);
    }

    public function getBlockPrefix(): string
    {
        return "answer_widget";
    }
}

src/Controller/Admin/ChallengeController.php
<?php

namespace App\Controller\Admin;

use App\Controller\BaseController;
use App\Entity\Challenge;
use App\Entity\ChallengeCategory;
use App\Form\ChallengeType;
use App\Repository\ChallengeRepository;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/admin/challenge")
 * @IsGranted("ROLE_ADMIN")
 */
class ChallengeController extends BaseController
{
    /**
     * @Route("/list/{category}", name="list_challenges")
     * @param ChallengeCategory $category
     * @param ChallengeRepository $repo
     * @return Response
     */
    public function indexAction(
        ChallengeCategory $category,
        ChallengeRepository $repo): Response
    {
        $challenges = $repo->findBy(['category' => $category], ['name' => 'asc']);

        return $this->render('challenge/challenge.index.html.twig', [
            'challenges' => $challenges,
            'category' => $category
        ]);
    }

    /**
     * @Route("/create/{category}", name="create_challenge")
     * @param Request $request
     * @param ChallengeCategory $category
     * @param ChallengeRepository $repo
     * @return Response
     */
    public function createChallengeAction(
        Request $request,
        ChallengeCategory $category,
        ChallengeRepository $repo): Response
    {
        $challenge = (new Challenge())->setCategory($category);
        $challenge->setPosition($repo->findPosition($category));
        return $this->editChallengeAction($request, $challenge, true);
    }

    /**
     * @Route("/edit/{challenge}", name="edit_challenge")
     * @param Request $request
     * @param Challenge $challenge
     * @param bool $adding
     * @return Response
     */
    public function editChallengeAction(
        Request $request,
        Challenge $challenge,
        bool $adding = false): Response
    {
        $form = $this->createForm(ChallengeType::class, $challenge);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($challenge);
            $em->flush();
            return $this->redirectToRoute('list_challenges', [
                'category' => $challenge->getCategory()->getId()
            ]);
        }
        return $this->render('challenge/challenge.edit.html.twig', [
            'form' => $form->createView(),
            'challenge' => $challenge,
            'adding' => $adding
        ]);
    }
}

src/Controller/ChallengeController.php
<?php

namespace App\Controller;

use App\Entity\Challenge;
use App\Entity\ChallengeCategory;
use App\Entity\ChallengeRun;
use App\Form\ChallengeType;
use App\Form\TakeChallengeType;
use App\Repository\ChallengeRepository;
use App\Services\ChallengeSelector;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ChallengeController extends AbstractController
{
    /**
     * @Route("/list-challenges/{category}", name="list_challenges")
     * @param ChallengeCategory $category
     * @param ChallengeRepository $repo
     * @return Response
     */
    public function indexAction(
        ChallengeCategory $category,
        ChallengeRepository $repo): Response
    {
        $challenges = $repo->findBy(['category' => $category], ['name' => 'asc']);

        return $this->render('challenge/challenge.index.html.twig', [
            'challenges' => $challenges,
            'category' => $category
        ]);
    }

    /**
     * @Route("/create-challenge/{category}", name="create_challenge")
     * @param Request $request
     * @param ChallengeCategory $category
     * @param ChallengeRepository $repo
     * @return Response
     */
    public function createChallengeAction(
        Request $request,
        ChallengeCategory $category,
        ChallengeRepository $repo): Response
    {
        $challenge = (new Challenge())->setCategory($category);
        $challenge->setPosition($repo->findPosition($category));
        return $this->editChallengeAction($request, $challenge, true);
    }

    /**
     * @Route("/edit-challenge/{challenge}", name="edit_challenge")
     * @param Request $request
     * @param Challenge $challenge
     * @param bool $adding
     * @return Response
     */
    public function editChallengeAction(
        Request $request,
        Challenge $challenge,
        bool $adding = false): Response
    {
        $form = $this->createForm(ChallengeType::class, $challenge);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $em->persist($challenge);
            $em->flush();
            return $this->redirectToRoute('list_challenges', [
                'category' => $challenge->getCategory()->getId()
            ]);
        }
        return $this->render('challenge/challenge.edit.html.twig', [
            'form' => $form->createView(),
            'challenge' => $challenge,
            'adding' => $adding
        ]);
    }

    /**
     * @Route("/take-challenge/{run}", name="take_challenge")
     * @param Request $request
     * @param ChallengeRun $run
     * @param ChallengeSelector $selector
     * @return Response
     */
    public function takeChallengeAction(
        Request $request,
        ChallengeRun $run,
        ChallengeSelector $selector): Response
    {
        $curr = $run->getCurrent();
        if (!$curr) {
            return $this->render('challenge/challenge.done.html.twig');
        }

        $form = $this->createForm(TakeChallengeType::class, null);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $next = $selector->findNext($curr, $run);

            // null is valid here, it means the run is over
            $run->setCurrent($next);

            $em = $this->getDoctrine()->getManager();
            $em->persist($run);
            $em->flush();

            return $this->render('challenge/challenge.result.html.twig', [
                'challenge' => $curr,
                'answer' => $form->get('answer')->getData(),
                'run' => $run
            ]);
        }

        return $this->render('challenge/challenge.html.twig', [
            'challenge' => $curr,
            'form' => $form->createView()
        ]);
    }
}

templates/challenge/challenge.done.html.twig
{% extends 'base.html.twig' %}

{% block title %}{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="alert alert-success mt-5 mx-5" role="alert">
        All challenges are done! Congrats!
    </div>
{% endblock %}

templates/challenge/challenge.edit.html.twig
{% extends 'base.html.twig' %}

{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block title %}
    {{ adding ? 'Add' : 'Edit' }} Challenge - {{ challenge.category.section }} - {{ challenge.category }}
{% endblock %}

{% macro answer(input) %}
<div data-delete-target class="answer row mt-1">
    <div class="col-11">{{ form_widget(input) }}</div>
    <div class="col-1">
        <button data-delete-button class="btn btn-secondary" type="button">x</button>
    </div>
</div>
{% endmacro %}

{% block body %}
    {{ parent() }}
    {{ form_start(form) }}
    <div class="row">
        <div class="col-8 mt-5 mx-5">
            {% if adding %}
                <h4>Add challenge</h4>
            {% else %}
                <h4>Edit {{ challenge.name }}</h4>
            {% endif %}
            <div class="mt-3">
                {{ form_row(form.name) }}
                {{ form_row(form.content) }}

                <div class="d-flex justify-content-between mb-3">
                    <label class="required">Answers</label>
                    <button class="btn btn-primary" type="button" id="challenge_add_answer">Add an answer</button>
                </div>

                <div id="challenge_answers"
                     class="mb-3"
                     data-prototype="{{ _self.answer(form.answers.vars.prototype)|e('html_attr') }}">

                    {% for answer in form.answers %}
                        {{ _self.answer(answer) }}
                    {% endfor %}
                </div>

                {{ form_row(form.link) }}
                {{ form_row(form.note) }}
            </div>
            <div class="float-right mt-2">
                <button class="btn btn-primary" type="submit">submit</button>
            </div>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script src="{{ asset('js/ChallengeController.js') }}"></script>
{% endblock %}

templates/challenge/challenge.html.twig
{% extends 'base.html.twig' %}

{% block title %}Challenge - {{ challenge.category.section }} - {{ challenge.category }}{% endblock %}

{% block body %}
    {{ parent() }}
    {{ form_start(form) }}
    <div class="mt-5 mx-5">
        <div class="mt-3 card">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <span class="text-lowercase">{{ challenge.category.section }} / {{ challenge.category }} / {{ challenge }}</span>
                    {% if challenge.link %}
                        <a href="{{ challenge.link }}" class="card-link">{{ challenge.category }} man page</a>
                    {% endif %}
                </div>
            </div>
            <div class="card-body">
                <p class="card-text pre">{{ challenge.content }}</p>
                <div class="mt-5">
                    {{ form_row(form.answer) }}
                </div>
            </div>
        </div>
        <div class="float-right mt-3">
            <button class="btn btn-primary" type="submit">submit answer</button>
        </div>
    </div>
    {{ form_end(form) }}
{% endblock %}

templates/challenge/challenge.index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Challenges{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="mt-5 mb-5 mx-5">

        <div class="d-flex justify-content-between">
            <h4>{{ category }} challenges</h4>
            <a href="{{ path('create_challenge', {'category' : category.id}) }}"
               class="btn btn-primary">
                Add challenge
            </a>
        </div>

        {% if challenges|length %}
            <div class="row mt-5">
                {% set half = (challenges|length) / 2|round(0, 'ceil') %}
                {% for column in challenges|batch(half, null) %}
                    <div class="col">
                        <ul class="list-group">
                            {% for challenge in column %}
                                {% if challenge %}
                                    <li class="list-group-item list-group-item-action">
                                        <div class="d-flex justify-content-between">
                                            {{ challenge }}
                                            {# <a href="{{ path('take_challenge', {'challenge': challenge.id}) }}">{{ challenge }}</a> #}
                                            <a href="{{ path('edit_challenge', {'challenge': challenge.id}) }}">edit</a>
                                        </div>
                                    </li>
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/challenge/challenge.result.html.twig
{% extends 'base.html.twig' %}

{% block title %}Challenge - {{ challenge.category.section }} - {{ challenge.category }}{% endblock %}

{% block body %}
    {{ parent() }}
    <div class="mt-5 mx-5">
        <div class="mt-3 card">
            <div class="card-header">
                <div class="d-flex justify-content-between">
                    <span class="text-lowercase">
                        {{- challenge.category.section }} / {{ challenge.category }} / {{ challenge -}}
                    </span>
                    {% if challenge.link %}
                        <a href="{{ challenge.link }}" class="card-link">{{ challenge.category }} man page</a>
                    {% endif %}
                </div>
            </div>
            <div class="card-body">
                <p class="card-text mb-3">
                    <span class="font-weight-bold">Result for</span>: {{ challenge.content }}
                </p>

                {% set answerNormalized = answer|replace({' ' : ''}) %}
                {% set possibleMatch = 0 %}

                {% for possibleAnswer in challenge.answers %}
                    {% set isSimilar = answerNormalized == possibleAnswer|replace({' ' : ''}) %}
                    <div class="card-text row">
                        <div class="col-2 font-weight-bold">{{ loop.first ? 'Possible answers' : '' }}</div>
                        <div class="col-10 {{ isSimilar ? 'text-success' : '' }}">{{ possibleAnswer }}</div>
                    </div>
                    {% set possibleMatch = possibleMatch + isSimilar %}
                {% endfor %}

                <div class="card-text row mt-3">
                    <p class="font-weight-bold col-2">Your answer</p>
                    <p class="col-10 {{ possibleMatch ? 'text-success' : '' }}"> {{ answer }}</p>
                </div>
            </div>
        </div>
        {% if challenge.note %}
            <div class="mt-3">
                <div class="alert alert-light">
                    Note: {{ challenge.note }}
                </div>
            </div>
        {% endif %}
        <div class="float-right mt-3">
            <a href="{{ path('take_challenge', {'run' : run.id}) }}" autofocus class="btn btn-primary">
                next challenge
            </a>
        </div>
    </div>
{% endblock %}